---
namespaces:
- name: portfolio-main
  owner: alphagov
  repository: portfolio-cluster-config
  branch: master
  path: config/portfolio-main
  requiredApprovalCount: 2
  ingress:
    enabled: true

- name: portfolio-pay
  owner: alphagov
  repository: pay-gsp-pipelines
  branch: master
  requiredApprovalCount: 0
  path: pipelines

- name: portfolio-pay-staging
- name: portfolio-pay-production

