---
namespaces:
- name: portfolio-main
  ingress:
    enabled: true

- name: portfolio-pay-test
  ingress:
    enabled: true
  owner: alphagov
  repository: pay-gsp-pipelines
  branch: develop
  requiredApprovalCount: 0
  path: ci/test

- name: portfolio-pay-prod
  ingress:
    enabled: true
  owner: alphagov
  repository: pay-gsp-pipelines
  branch: develop
  requiredApprovalCount: 0
  path: ci/prod
